name: Cypress E2E Tests

on: push

jobs: 
          
  cypress-run-ui-tests:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Cypress run
        uses: cypress-io/github-action@v6
        